### ISSUE TITLE
0.3.2 json decode failed due to "+"

### ISSUE THREAD

**Issue by wwwjk366** [trestletech/plumber#105]
I was using 0.3.1 and my function is recieveing some json string then decode in R with no problem. After I upgrade to 0.3.2 my fucntion failed because the json string I recieved has "+" in it.\

"{\"user_id\":+[\"dfdfdf\"],+\"channel_id\":+[\"dfdf\"],+..."

Maybe the update messed up the urldecoder?

**Comment by trestletech** [comment]
Can you please provide a minimally reproducible example?

**Comment by wwwjk366** [comment]
I would love to but my setup is a bit complicated to replicate into a reproducible.

basically i have a AWS lambda function that will send json payload to my url:

payload = {'command': res, 'url': res_url, 'channel': channel}
r = requests.get(url, payload, timeout=1.5)

then url is my plumber endpoint which i do this 


#* @get /func
func <- function(command, url, channel) {  
  json_cmd <-jsonlite:: fromJSON(channel)
....

then the fromJSON will fail because if I print 'channel' it looks like this:

 "{\"user_id\":+[\"adfasdf\"],+\"channel_id\":+[\"asdfasdf\"],+\"text\":+[\"asdfasdf\"],+\"response_url\":..."

If I use plumber 0.3.1, i will get this
 "{\"user_id\": [\"asdfadsf\"], \"channel_id\": [\"adsfadsf\"], \"text\": [\"asdfasdf\"],...."

which is more ok as a JSON

**Comment by trestletech** [comment]
I'm unable to reproduce any buggy behavior so without a minimally reproducible example I won't be able to proceed with this one, sorry.

Here's what I'm using

```
#' @post /
function(a){
  a
}
```

```
curl --data '{"a": "hi+there"}' localhost:8000/
["hi+there"]
```

See issue #81 for why this would be different in 0.3.2, though. I think what you're seeing is a URL encoding problem coming from Lambda that use to be suppressed and accidentally work because of the bug in #81, but now that that's been fixed the errant `+`s are breaking things.

I don't know of a reason why plumber would be inserting plusses in your JSON body, so I'm pessimistic that the bug is in plumber itself.

Feel free to reopen if you're able to come up with a reproducible example that I'd be able to run myself.
