### ISSUE TITLE
Question: Missing something fundamental with regards to accessing 'req' list

### ISSUE THREAD

**Issue by vfulco** [trestletech/plumber#201]
Per #184, mailgun sends a list of parameters to an HTTP POST.  I can access plumber's full list of req using print(ls(req)).  The first item is 'args'.  I assume 'args' is all the parameters found in the POST request?  

#* @post /mail
#* @get /mail
function(req,res){
    print(req[['args']])
}

When I try to print one level deeper to access each component of the forwarded email using print(req$args) or print(req[['args']], I get a 500 error.  TIA.

**Comment by trestletech** [comment]
The problem is that `print` silently returns the object that it prints. So your API is actually trying to return the `req$args` object which jsonlite can't figure out how to serialize because it has complex R6 objects in it.

```
#* @post /mail
#* @get /mail
function(req,res){
  print(req[['args']])
  123 # return something serializable
}
```

works for me.

Also note that calling `browser()` in your endpoint can be a nice way to interactively explore these objects rather than printing them and having to rebuild your API every time.
