### ISSUE TITLE
Implement async

### ISSUE THREAD

**Issue by trestletech** [trestletech/plumber#204]
Following httpuv's implementation of async, we should add an async implementation to plumber endpoints/filters.

**Comment by schloerke** [comment]
Closed in #248

**Comment by jeffkeller87** [comment]
FYI, there is a low-level and somewhat artificial [performance issue](https://stat.ethz.ch/pipermail/r-devel/2020-November/080069.html) in the `parallel` package on Linux. In effect, it puts a 35-45ms floor on data transfers between `parallel` socket connections.

For most `parallel` use-cases this penalty isn't noticeable. But for use-cases like `plumber` it is often quite noticeable if you are looking to achieve industry acceptable levels of API performance (which you probably are if you're going parallel). This has also been brought up regarding the `future` package: https://github.com/HenrikBengtsson/future/issues/437

I'd love to see the `plumber` community press R-devel to implement the fix, since we are the sort of use-case affected. I unfortunately do not have the skills to contribute such a low-level change to `parallel`.

**Comment by meztez** [comment]
Even if they implement the fix, it would not impact plumber since plumber relies on libuv from httpuv package.

TCP_NODELAY would have to be enabled from httpuv library.

**Comment by jeffkeller87** [comment]
My bad. I saw references to `promises` and assumed the `future` package was involved.
