### ISSUE TITLE
connections reset

### ISSUE THREAD

**Issue by stevendingcheng** [trestletech/plumber#214]
The API works good, and the server print the msg “ERROR: [on_request_read] connection reset by peer” 
I guess it happens when the client try to close the connection, is there any proposal how to ignore the error message?

Java code like this: 
CloseableHttpClient client = (enableSSL) ? createSSLClient() : HttpClients.createDefault();
CloseableHttpResponse response = null;
HttpPost post = new HttpPost(url);
post.setConfig(REQUEST_CONFIG);
// [Content-Type: application/json; charset=UTF-8,Content-Length:
// xx,Chunked: false]
post.setEntity(new StringEntity(json, ContentType.APPLICATION_JSON));
response = client.execute(post);
response.close();

ps. the same request works fine by using the postman and no connection reset errors print.

**Comment by trestletech** [comment]
Unfortunately I think this would be a property of the underlying httpuv library. https://github.com/rstudio/httpuv You could consider opening an issue there if you think it's something important for that library to handle. 

I'll close this issue for now, though, since I don't see a great way for plumber to handle this internally in the foreseeable future.
