### ISSUE TITLE
Could you clarify your license?

### ISSUE THREAD

**Issue by pa009fa** [trestletech/plumber#250]
Hi,

We are really interested to move from OpenCPU to Plumber for performance reasons but our corporate IT guys wanted to make sure which license the system is released under. The LICENSE file doesnt contain any information but the source code refers to "MIT + file". 

Could you clarify the situation and, if possible, update the LICENSE file?

Thanks.

**Comment by trestletech** [comment]
Sorry, this is the R package convention. CRAN doesn't like having the redundant copies of license text, for some reason so this is how they insist packages structure things.

Plumber is made available under the standard MIT license.

**Comment by pa009fa** [comment]
Thanks. I'll run that by our bureaucrats and see if they are ok.

**Comment by LeZhengThu** [comment]
Hi,
     I also have concerns about the license. The LICENSE file claims the copyright holder is Trestle Technology, LLC. And after I search keyword license in Issues, I find this. The license is really misleading.

**Comment by dipterix** [comment]
Hi, 

I found out that although `plumber` is released under MIT license, the dependence `httpuv` is released under GPL license. Does that make plumber GPL as a whole since it is unlikely to without `httpuv`? Though code under plumber which doesn't depend on `httpuv` still remains MIT.

If I develop some applications with plumber, then I need to include httpuv which is released under GPL term. Then if I want to release my application, the application still need to be under GPL as a whole...

**Comment by schloerke** [comment]
I am not a lawyer, this is my opinion.

---------------

R is `GPL-2`: https://www.r-project.org/Licenses/

WIth in the `Copyleft` bullet point in https://r-pkgs.org/license.html:
> Copyleft licenses are stricter. The most common copyleft license is the [GPL](https://choosealicense.com/licenses/gpl-3.0/) which allows you to freely copy and modify the code for personal use, but if you publish modified versions or bundle with other code, the modified version or complete bundle must also be licensed with the GPL.

The `{plumber}` package does not bundle any `{httpuv}` code **within** the CRAN package. However it does _use_ `{httpuv}` once it is loaded.  For typical CRAN packages, this works great as we are not using a modified source of `{httpuv}` within our package `{plumber}`.

However, if you were to physically copy `{httpuv}` code into your personal R package and distribute that code, then your R package must by **copyleft** compatible.  This same logic applies in that if you bundle R in your distributed code, it must also be **copyleft compatible**

**Comment by dipterix** [comment]
Just to clarify, I guess no matter `plumber` is released under MIT or not, users who distribute their work under plumber are subject to GPL license since `plumber`+`httpuv` is clearly GPL. So basically their codes are still subject to GPL, and not publishing the software under the GPL would be copyright infringement.

**Comment by schloerke** [comment]
[R itself is `GPL-2`](https://www.r-project.org/Licenses/). If anything, by using R, your application would need to be GPL. 

---------------------------------

Locking this issue to stop spamming 4 yr old subscribers. 

Please reference this issue in a new issue if you'd like to continue the conversation.
