### ISSUE TITLE
Update documentation?

### ISSUE THREAD

**Issue by EDiLD** [trestletech/plumber#311]
Hi folks,

I really like the bookdown documentaion for plumber. 
Nevertheless, I have a feeling that there is a lot in plumber that I don't know, simply because it's not documented. Working through the sources is possible, but very tedious...

There are some quite parts missing (`\\TODO`) is it planned to update these?

**Comment by shizidushu** [comment]
@schloerke @trestletech  I have the same feeling too.  The documentation's edit button points to https://github.com/trestletech/apis-plumber. It's almost not updated in recent months.

**Comment by trestletech** [comment]
Yup! We're continuing to chip away at the documentation as time allows. Unfortunately, time has not allowed much in recent months.

If there's a particular section that you'd be willing to contribute documentation for, please let us know and I can give you all the code pointers and review the docs once you put them together. Otherwise, we'll keep pushing forward on the docs as quickly as we're able to.
