### ISSUE TITLE
Support for 'batch' mode, i.e. multiple lines of input data

### ISSUE THREAD

**Issue by FrankPortman** [trestletech/plumber#40]
I'm looking for a way to be able to pass in multiple lines of data in the form of 

    'curl --data "a=1&b=2\na=3&b=4\n..."

My specific use case would benefit a lot from being able to read in vectors of data in this way and then converting to a data frame within the function I am exposing as an API. To simplify, you can think of me simply passing in the contents of a .csv file.

You can see my attempt at reverse engineering your package here: https://github.com/FrankPortman/plumber. 

I went into query-string.R and created a slightly modified parseQS function called parseQS2. I'm trying to mimic the exact format that parseQS returns, but in my case it's returning vectors of length > 1 in each sublist, as opposed to just 1 like you have. I then change the function in queryStringFilter from using parseQS to using parseQS2. However, it seems like when I pass in multiple lines of data, it is correctly doing the parseQS2 step (at least it looks that way from the traceback) but somewhere along the way some variables get dropped.

```
#* @post /test
function(a, b) {

  return(list(sum(as.numeric(a) + as.numeric(b)),
  as.numeric(a),
  as.numeric(b)))

}
```

    curl --data "a=2&b=15 \n a=1&b=4 \n a=1&b=2" "http://localhost:1234/test"
    [[4],[2],[2]]

It looks like only the first a and the last b is being evaluated.

    curl --data "a=2&b=15 \n a=1&b=4" "http://localhost:1234/test"
    [[6],[2],[4]

Before I dive deeper into this myself, are there any functions of specific pieces of code I would have to look into modifying in order to do something like this? 

P.S. - I thought about approaching this problem from the other side (taking in only one line of named arguments but somehow encapsulating all the 'rows' I want to pass) but this approach seems cleaner if I can get it to work. Not sure if this is the best way of approaching my use case but if there is any interest from you/others on this functionality I'd be more than happy to discuss with you how this can potentially fit in with the package's architecture and help write tests for it so it can be merged eventually. For now, I'm just treating it as a one-off case for myself and am not too concerned with error handling so feel free to suggest something hacky.

**Comment by trestletech** [comment]
Hi Frank,

How much control do you have over the client sending the data? It seems to me that alternative formats might be a better fit for this structure of data. I'm thinking for instance that you could pass in JSON a la `endpoint?data="[{a:1, b:2}, {a:3, b:4}]` and parse the data frame out in that way.

I'm pushing back just because any time I've had to work with repeated query string parameters in any programming language/framework, it's always felt cludgy. So that idea makes me a little reserved about diving in to support the feature (though of course you can do whatever you want in your fork!).

I don't see any obvious problems with the method you proposed, nor am I sure why you'd be getting those errors, but I'm not totally surprised that it didn't work. I can imagine that some list of arguments to pass in is being indexed by parameter name, so as it encounters multiple parameters with the same name some get dropped or something.

**Comment by FrankPortman** [comment]
Hi,

Thanks for the quick reply.

Actually I ended up being able to fix it. The issue was curl being unhappy with newline characters in the data argument. If you do the curl command with a file input instead:

    curl --data "`cat test_file`"

or

    curl --data-binary @test_file 

then it seems to work as expected. A side benefit is that passing in just one row still works!

I've considered doing it the way you are suggesting as well and then unwrapping it within the function itself and I may end up going that route in the future. Is there anywhere you can point me to to learn more about the JSON input format you're suggesting? I'm only used to interfacing with plumber using --data "a=1&b=2...".

**Comment by trestletech** [comment]
I don't have a formal reference on the topic, but you could look at serializing with `jsonlite::toJSON()` and within your plumber function deserializing using `jsonlite::fromJSON()`. In that case, the variable you're trying to parse is just a string. 

That format seems a little more typical, at least from what I've seen, but I don't know that there are any compelling reasons to prefer it over your approach.
