### ISSUE TITLE
Up-time and advice for running plumber on Windows

### ISSUE THREAD

**Issue by krose** [trestletech/plumber#47]
This is not an issue but a general question on the stability of this on a Windows Server.

I don't have any experience with this package, other than getting the examples to work, but it seems like an easy and good way to host an API (with low volume). My basic concern is that I have to restart the process all the time.

Does any one have experience with running plumber on a Windows (Virtual Server) and have some valuable advice to share? A Linux Server is not a possibility at my company.

**Comment by trestletech** [comment]
I unfortunately don't have access to a Windows machine, so I may not be of much help here but perhaps someone else can chime in with their experiences.

The one lead I might be able to provide is a pointer to Docker. I have detailed docs on how to run plumber in Docker in a hosting environment here: http://plumber.trestletech.com/docs/docker/

Docker is supported in Windows, though it historically required a bit of hacking. My understanding is that this is becoming smoother and smoother in recent months, so it might be worth looking into if you hadn't already. I don't know if that counts as a Linux server per your IT department, but that might be the best bet.

Otherwise you'd need to wrap it in some service that Windows knows how to start and keep alive. I'm sure there are libraries/systems available for that but I unfortunately don't know them.

**Comment by krose** [comment]
Thank you for the response. 

I have already thought about Docker but virtualization isn't supported on the machine I have available.

I think I'll try to expose one of the more simple scripts for a period and see how it runs. I'll weigh in with my experience later in a comment.
