### ISSUE TITLE
Allowing 'source' to structure code

### ISSUE THREAD

**Issue by semuelle** [trestletech/plumber#56]
When a plumber server offers lots of functionality, the plumbed file is bound to get very large. It would be very helpful in terms of readability and maintainability if the code could be spread among several files, which are then just `source`d into one big file.

**Comment by trestletech** [comment]
(sorry for the slow response.) The approach I had envisioned for this functionality was #36. In which you could compartmentalize your API by URL prefixes, so you could have a `/cars` router for all car-related API activity, and then a `/bikes` router for the bike portion of the API. Then you could stack those together so that your API has both `/bike/WHATEVER` and `/api/BLAH` paths available.

Is there a reason to prefer `source`'ing over that? Or what that meet your needs?

**Comment by semuelle** [comment]
Thanks for the response. There is no specific reason for `source`. Any way to structure my code would be great. I had not seen #36.
