### ISSUE TITLE
Suggestion: Allow JSON unboxing 

### ISSUE THREAD

**Issue by ruipaulo** [trestletech/plumber#69]
I am a first-time plumber user so I hope this suggestion is on topic.

When using plumber I was wondering why each value was surrounded by [ ] in json. Of course, this is R-typical, but it makes consuming the output in JS harder. 

Jsonlite allows to unbox single values of vectors automatically. 

I was looking for a solution and did not find one, except writing a custom serializer.
This serializer is exactly the same as your jsonSerializer, except it has the jsonLite Auto-unboxing parameter set to True (  json <- jsonlite::toJSON(val,auto_unbox = T)).

I think that the option to unbox single element vectors would be useful for many users.

**Comment by yogesh-bansal** [comment]
I think this can be done using adding another JSON serializer and explicitly call the serializer while defining the function. I have asked and answered it [here](http://stackoverflow.com/questions/41965032/r-plumber-json-serializer-auto-unbox).

**Comment by ruipaulo** [comment]
Thanks for the link, I think it is a good resource for people with the same problem. 
I am currently doing the same, but I think it should be the **default** behavior. Otherwise every property is a list, which is very R like, but not very JSON'ish.

**Comment by trestletech** [comment]
Had a bit more discussion on this in #80.

I'm not opposed to this change long-term and could agree that it might be a bug that it's not the default behavior. Unfortunately I feel like we're locked in for right now since this would be a backwards incompatible change.

For now I'd like to make it easier to get the auto_unboxing behavior that you describe, but I'd want to wait until a major version bump before I consider changing the default behavior in a backwards incompatible way. I'll leave this issue open until we make progress on either front.

**Comment by trestletech** [comment]
Actually I'll close this as a dup of #55, but we'll track the open issue there.
