### ISSUE TITLE
Automatically publish roxygen headers with endpoints

### ISSUE THREAD

**Issue by sellorm** [trestletech/plumber#76]
It would be really cool if, when a file is plumbed, roxygen headers associated with the plumbed function become available via a special url.

For example, if you have an endpoint at `/endpoint`, it would be great if a nicely formatted html version of the roxygen header associated with the function/endpoint were published at `/endpoint/__docs__`. It would be nicer still, if a json representation of the docs was then available at `/endpoint/__docs__/json`.

I currently do something similar manually, using an Rmd file with the documentation in it and the `include_rmd` function. It would be great to use roxygen headers instead though as this keeps everything in a single file and is a pattern with which a great many R devs are already familiar.

This aids in documentation discoverability and having them also available in json would mean all docs could be aggregated simply. Perhaps there should also be some config option to turn this on/off.

**Comment by trestletech** [comment]
I've been thinking about offering a [JSON Schema](http://json-schema.org/) of a plumber API. But haven't had time to totally flesh out that idea yet...

**Comment by trestletech** [comment]
I'm thinking I'll close this in favor of #86, but speak up if you think there are features here that would be missing from that approach.

It wouldn't be exactly Roxygen unfortunately because you need more information (like data types). So it would have to be either an alternative syntax to roxygen or at least add some extra features into the format Roxygen expects.
