### ISSUE TITLE
Serving Plumber api endpoints on HTTPS SSL

### ISSUE THREAD

**Issue by daxil001** [trestletech/plumber#99]
I am using RApache (Apache server with R_mod) and I'm using plumber to create api endpoints for my web application. RApache server is hosted on HTTPS (SSL).  But, when i use plumber api, it is creating endpoint on http://{{some-port}} 

Is it possible to serve plumber APIs on https so that my server can communicate easily with client?

Any suggestions appreciated.
Thanks

**Comment by trestletech** [comment]
Yes. Plumber itself doesn't do SSL but you can have a service in front of plumber that terminates SSL.

See https://plumber.trestletech.com/docs/digitalocean/ for the easiest way to setup a plumber server with SSL on DigitalOcean, or you can look at the implementation of those commands to see how to do it on your own server.

**Comment by jnolis** [comment]
Is there any chance of this being implemented in the future? I am looking to use plumber in an enterprise environment so encryption is really important.

**Comment by nuest** [comment]
My suggestion would be to run plumber behind an HTTP server (nginx, Apache), because they are really good at https, that's what they are build for. If you worry about security, I would say it is better to use something many others apply than re-implementing this in plumber (even not knowing the efforts required for that).

**Comment by francisliyy** [comment]
Does anybody have a solution for https when using Docker to deploy plumber?
